name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Format Check
        run: bun run format

      - name: Lint Check
        run: bun run lint

      - name: Type check
        run: bun run typecheck

      - name: Build
        run: bun run build